# **Pandas**

---

## Introduction

### Basics

#### What is Pandas?
Pandas is a Python library used for data manipulation and analysis. Pandas provides a convenient way to analyze and clean data.
The Pandas library introduces two new data structures to Python - Series and DataFrame, both of which are built on top of NumPy.

#### What is Pandas Used for?
Pandas is a powerful library generally used for:
- Data Cleaning
- Data Transformation
- Data Analysis
- Machine Learning
- Data Visualization

#### Why Use Pandas?
- Handle Large Data Efficiently
- Tabular Data Representation
- Data Cleaning and Preprocessing
- Time Series Functionality
- Free and Open-Source

#### How to install and import Pandas?

To install Pandas, run: `pip install pandas` if not altready installed.  
To import Pandas (and NumPy just in case):

In [1]:
import numpy as np
import pandas as pd

### Series

**Series:** It is a one-dimensional labeled array-like object that can hold data of any type.
1. It can be thought of as a column in a spreadsheet or a single column of a DataFrame.  
2. It consists of two main components: the labels and the data:
   - The labels are the index values assigned to each data point, while
   - The data represents the actual values stored in the Series.

In [2]:
s = pd.Series([1, 2, 3, 4, 5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

Here, the dtype is int64 because all the elements of the series are of int64 type.  
The labels in the Pandas Series are index numbers by default. We can use these labels to access a specified value:

In [3]:
s[2]

3

So, here we got the element 3 which has index 2. We can specify custom indices while creating a series:

In [4]:
s_one = pd.Series([10, 20, 30, 40, 50], index=['one', 'two', 'three', 'four', 'five'])
s_one

one      10
two      20
three    30
four     40
five     50
dtype: int64

We can also use these indices to access the elements:

In [5]:
s_one['four']

40

So, here we got the element 40 which has index 'four'. We can also create a series from a Python dictionary:

In [6]:
pd.Series({"Alice": 85.5, "Bob": 78.2, "Charlie": 92.8, "David": 65.7, "Eve": 100})

Alice       85.5
Bob         78.2
Charlie     92.8
David       65.7
Eve        100.0
dtype: float64

Here, we created a series of names as indices and floating-point marks as data.  
We can also create a series using specific keys from a Python dictionary:

In [7]:
data_one = {'sem 1': '98.00', 'sem 2': '76.78', 'sem 3': '89.44', 'sem 4': '45.57', 'sem 5': '67.41'}
pd.Series(data_one, index=['sem 1', 'sem 2', 'sem 5'])

sem 1    98.00
sem 2    76.78
sem 5    67.41
dtype: object

### DataFrame

**DataFrame:** A DataFrame is like a table where the data is organized in rows and columns.
1. It is a two-dimensional data structure like a two-dimensional array.
2. Each row represents a record, with the index value on the left.
3. The index values are auto-assigned starting from 0.
4. The DataFrame is similar to a table in a SQL database, or a spreadsheet in Excel.
5. It is designed to manage ordered and unordered datasets in Python.

We can create a Pandas DataFrame in the following ways:
- Using Python Dictionary
- Using Python List
- From a File
- Creating an Empty DataFrame

##### Create a DataFrame using Python Dictionary

In [8]:
pd.DataFrame({'name': ["Alice", "Bob", "Charlie", "David", "Eve"], 'marks': [85.5, 78.2, 92.8, 65.7, 100]})

name  marks
0    Alice   85.5
1      Bob   78.2
2  Charlie   92.8
3    David   65.7
4      Eve  100.0

Here we got a DataFrame of 2 columns and 5 rows.

##### Create a DataFrame using Python List

In [9]:
pd.DataFrame([["Alice", "Bob", "Charlie", "David", "Eve"], [85.5, 78.2, 92.8, 65.7, 100]], ['name', 'marks'])

0     1        2      3    4
name   Alice   Bob  Charlie  David  Eve
marks   85.5  78.2     92.8   65.7  100

Here we got a DataFrame of 5 columns and 2 rows.

In [10]:
pd.DataFrame([["Alice", 85.5], ["Bob", 78.2], ["Charlie", 92.8], ["David", 65.7], ["Eve", 100]], columns=['name', 'marks'])

name  marks
0    Alice   85.5
1      Bob   78.2
2  Charlie   92.8
3    David   65.7
4      Eve  100.0

Here we got a DataFrame of 2 columns and 5 rows.

##### Create a DataFrame using NumPy Array

In [11]:
pd.DataFrame(np.array([
    ["Alice", 85.5], 
    ["Bob", 78.2], 
    ["Charlie", 92.8], 
    ["David", 65.7], 
    ["Eve", 100]
]), columns=np.array(['name', 'marks']))

name marks
0    Alice  85.5
1      Bob  78.2
2  Charlie  92.8
3    David  65.7
4      Eve   100

##### Create an Empty DataFrame

In [12]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

Here, both the columns and indices are empty in the DataFrame. The DataFrame has no data, but it can be used as a container to store and manipulate data later.

### Index

Let's talk more about the indices.  
**Index:** In Pandas, an index refers to the labeled array that identifies rows or columns in a DataFrame or a Series.

#### Creating Indices

When we create a DataFrame or Series without specifying an index explicitly, Pandas assigns a default integer index starting from 0.

In [13]:
pd.DataFrame({'city': ['Satara', 'Pune', 'Mumbai', 'Nagpur'], 'temperature': [25, 34, 34, 38]})

city  temperature
0  Satara           25
1    Pune           34
2  Mumbai           34
3  Nagpur           38

As we can see, the default indices are assinged for each row in the DataFrame.  
Or, we can set a column as index:

In [14]:
pd.DataFrame({'city': ['Satara', 'Pune', 'Mumbai', 'Nagpur'], 'temperature': [25, 34, 34, 38]}).set_index('city')

temperature
city               
Satara           25
Pune             34
Mumbai           34
Nagpur           38

Here, the city column became the index. We can also create a range index:

In [15]:
pd.DataFrame({'city': ['Satara', 'Pune', 'Mumbai', 'Nagpur'], 'temperature': [25, 34, 34, 38]}, index=pd.RangeIndex(12, 16, name='index'))

city  temperature
index                     
12     Satara           25
13       Pune           34
14     Mumbai           34
15     Nagpur           38

We put index range from 12 to 16 because the last number is not included in the range. Here we got the column named index with indices 12, 13, 14 and 15.

#### Modifying Indices

In [16]:
s_two = pd.DataFrame({'city': ['Satara', 'Pune', 'Mumbai', 'Nagpur'], 'temperature': [25, 34, 34, 38]})
s_two

city  temperature
0  Satara           25
1    Pune           34
2  Mumbai           34
3  Nagpur           38

We can rename an index like this:

In [17]:
s_two.rename(index={0: 'A', 1: 'B', 2: 'C', 3: 'D'})

city  temperature
A  Satara           25
B    Pune           34
C  Mumbai           34
D  Nagpur           38

Here, the capital alphabets replaced the default indices.  
We can reset the index to the default integer index too, like this:

In [18]:
s_three = s_two.rename(index={0: 'A', 1: 'B', 2: 'C', 3: 'D'})
s_three

city  temperature
A  Satara           25
B    Pune           34
C  Mumbai           34
D  Nagpur           38

In [19]:
s_three.reset_index()

index    city  temperature
0     A  Satara           25
1     B    Pune           34
2     C  Mumbai           34
3     D  Nagpur           38

Here, the indices have been reset to the default values, although there is a new column with name index which has our previous indices.

#### Access Rows by Index

##### Using iloc Property

iloc is used to access elements on the basis of default index:

In [20]:
s_two.iloc[2]

city           Mumbai
temperature        34
Name: 2, dtype: object

Here we got the data from default index 2.

##### Using loc Property

To access elements based on the custom indexing, we can use loc property:

In [21]:
s_three.loc['A']

city           Satara
temperature        25
Name: A, dtype: object

We can also use loc for default indexing:

In [22]:
s_two.loc[2]

city           Mumbai
temperature        34
Name: 2, dtype: object

**Note:** As we used custom indexing on s_three and then again reset it to the default index, we can only use iloc for default indices and loc for custom indices there.

#### Modifying element values

We can also use loc and iloc to change the elements:

In [23]:
s_three.loc['C', 'temperature'] = 40
s_three

city  temperature
A  Satara           25
B    Pune           34
C  Mumbai           40
D  Nagpur           38

In [24]:
s_two.iloc[0, s_two.columns.get_loc('temperature')] = 20
s_two

city  temperature
0  Satara           20
1    Pune           34
2  Mumbai           34
3  Nagpur           38

Here, columns.get_loc() method returned the location of temperature column. We did this because iloc indices need all the values as integers.

#### Types of Indices

| Type                                | Description                                                                                                     |
|-------------------------------------|-----------------------------------------------------------------------------------------------------------------|
| Range Index (RangeIndex)            | It represents a sequence of integers within a specified range. <br> It is of type int64. The range index [0, 1, 2, ...] is often used as the default index when creating DataFrame. |
| Categorical Index (CategoricalIndex)| It is used when dealing with categorical data. It stores a fixed set of unique categorical values.              |
| Datetime Index (DatetimeIndex)      | It is used when working with time series data. It is of type datetime64.                                       |
| Range Index (RangeIndex)            | It represents a sequence of integers within a specified range. It is of type int64. The range index [0, 1, 2, ...] is often used as the default index when creating DataFrame | [0, 1, 2, 3, 4, 5, 6], [100, 101, 102, 103, 104]                                                 |
| Categorical Index (CategoricalIndex)| It is used when dealing with categorical data. It stores a fixed set of unique categorical values.              | ['Red', 'Green', 'Blue', 'Red', 'Blue'], ['Category A', 'Category B', 'Category C', 'Category A', 'Category B'] |
| Datetime Index (DatetimeIndex)      | It is used when working with time series data. It is of type datetime64                                          |                                                                                                |
| Multi Index (MultiIndex)            | It allows us to have multiple levels of indexing on one or more axes of a DataFrame or a Series object.          |                                                                                                |
| Interval Index (IntervalIndex)      | It is used to represent intervals or ranges of values in pandas.                                                 |                                                                                                |
| Timedelta Index (TimedeltaIndex)    | It represents a sequence of time durations. Each element in the index represents a specific duration of time, such as hours, minutes, seconds, or a combination of these. |                                                                                                |
| Period Index (PeriodIndex)          | It represents a sequence of time periods. Each element in the index represents a specific time period, such as a day, month, quarter, or year. |                                                                                                |


### Array

Pandas array is designed to provide a more memory-efficient and performance-enhanced alternative to Python's built-in lists, NumPy arrays, and other data structures for handling the same type of data.  
We can create an array like this:

In [25]:
pd.array([1, 2, 3, 4, 5])

<IntegerArray>
[1, 2, 3, 4, 5]
Length: 5, dtype: Int64

We can also specify the dtype of the array:

In [26]:
pd.array([1, 2, 3, 4, 5], dtype='float')

<NumpyExtensionArray>
[1.0, 2.0, 3.0, 4.0, 5.0]
Length: 5, dtype: float64

Here, as we set the dtype as 'float', we got a float64 array.  
We can also create a series using an array:

In [27]:
pd.Series(pd.array([1, 2, 3, 4, 5]))

0    1
1    2
2    3
3    4
4    5
dtype: Int64

## Dataframe Operations and Manipulations

### DataFrame Analysis

#### View Data

In the case of large DataFrames, we can use head(), tail(), info() and description() methods to get the overview of the DataFrame.
- **head():** It returns the column headers and a specified number of rows from the beginning.
- **tail():** It returns the column headers and a specified number of rows from the end.
- **info():** It gives the overall information about the DataFrame such as its class, data type, size etc.
- **describe():** It gives the overall statistical information about the DataFrame such as count, min, max etc.

Let's first extend our city-temperature DataFrame:

In [28]:
cities_temps = pd.DataFrame({
    'city': ['Satara', 'Pune', 'Mumbai', 'Nagpur', 'Nashik', 'Chh. Sambhajinagar', 'Kolhapur', 'Solapur', 'Amravati', 'Thane'], 
    'temperature': [25, 34, 34, 38, 28, 36, 27, 35, 37, 32]
})
cities_temps

city  temperature
0              Satara           25
1                Pune           34
2              Mumbai           34
3              Nagpur           38
4              Nashik           28
5  Chh. Sambhajinagar           36
6            Kolhapur           27
7             Solapur           35
8            Amravati           37
9               Thane           32

##### head() method

In [29]:
cities_temps.head()

city  temperature
0  Satara           25
1    Pune           34
2  Mumbai           34
3  Nagpur           38
4  Nashik           28

head() method selected the first 5 rows by default. If we want a custom number of rows from the top:

In [30]:
cities_temps.head(3)

city  temperature
0  Satara           25
1    Pune           34
2  Mumbai           34

Here, we selected the first 3 rows.

##### tail() method

In [31]:
cities_temps.tail()

city  temperature
5  Chh. Sambhajinagar           36
6            Kolhapur           27
7             Solapur           35
8            Amravati           37
9               Thane           32

tail() method selected the last 5 rows by default. If we want a custom number of rows from the bottom:

In [32]:
cities_temps.tail(4)

city  temperature
6  Kolhapur           27
7   Solapur           35
8  Amravati           37
9     Thane           32

Here, we selected the last 4 rows.

##### info() method

It returns:
- The class of the object, which indicates that it is a pandas DataFrame.
- The index range of the DataFrame, showing the starting and ending index values.
- The total number of columns in the DataFrame.
- The names of the columns in the DataFrame.
- The count of non-null values for each column.
- The data types of the columns.
- The memory usage of the DataFrame in bytes.

In [33]:
cities_temps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   city         10 non-null     object
 1   temperature  10 non-null     int64 
dtypes: int64(1), object(1)
memory usage: 288.0+ bytes


##### describe() method

In [34]:
cities_temps.describe()

temperature
count    10.000000
mean     32.600000
std       4.477102
min      25.000000
25%      29.000000
50%      34.000000
75%      35.750000
max      38.000000

### DataFrame Manipulation

In [35]:
guys = pd.DataFrame({
    "name": ["John", "Mike", "Chris", "David", "James", "Robert", "Daniel", "Matthew", "Andrew", "Joshua"],
    "age": [25, 30, 22, 27, 35, 28, 24, 33, 26, 29],
    "height": [175, 180, 170, 178, 185, 177, 182, 174, 180, 176],
    "qualification": ["Bachelor's", "Master's", "Bachelor's", "PhD", "Master's", "Bachelor's", "Master's", "PhD", "Bachelor's", "Master's"]
})
guys

name  age  height qualification
0     John   25     175    Bachelor's
1     Mike   30     180      Master's
2    Chris   22     170    Bachelor's
3    David   27     178           PhD
4    James   35     185      Master's
5   Robert   28     177    Bachelor's
6   Daniel   24     182      Master's
7  Matthew   33     174           PhD
8   Andrew   26     180    Bachelor's
9   Joshua   29     176      Master's

#### Add a New Column to a DataFrame

We can add a new column to an existing DataFrame by simply declaring a new list as a column:

In [36]:
guys['city'] = ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose"]
guys

name  age  height qualification          city
0     John   25     175    Bachelor's      New York
1     Mike   30     180      Master's   Los Angeles
2    Chris   22     170    Bachelor's       Chicago
3    David   27     178           PhD       Houston
4    James   35     185      Master's       Phoenix
5   Robert   28     177    Bachelor's  Philadelphia
6   Daniel   24     182      Master's   San Antonio
7  Matthew   33     174           PhD     San Diego
8   Andrew   26     180    Bachelor's        Dallas
9   Joshua   29     176      Master's      San Jose

Here, we added the city column in the DataFrame.

#### Add a New Row to a DataFrame

Adding rows to a DataFrame is not quite as straightforward as adding columns. We use the .loc property to add a new row to a DataFrame:

In [37]:
guys.loc[len(guys.index)] = ["Alex", 23, 179, "Bachelor's", "Austin"]
guys

name  age  height qualification          city
0      John   25     175    Bachelor's      New York
1      Mike   30     180      Master's   Los Angeles
2     Chris   22     170    Bachelor's       Chicago
3     David   27     178           PhD       Houston
4     James   35     185      Master's       Phoenix
5    Robert   28     177    Bachelor's  Philadelphia
6    Daniel   24     182      Master's   San Antonio
7   Matthew   33     174           PhD     San Diego
8    Andrew   26     180    Bachelor's        Dallas
9    Joshua   29     176      Master's      San Jose
10     Alex   23     179    Bachelor's        Austin

#### Delete a Column from a DataFrame

In [38]:
guys.drop('qualification', axis=1)

name  age  height          city
0      John   25     175      New York
1      Mike   30     180   Los Angeles
2     Chris   22     170       Chicago
3     David   27     178       Houston
4     James   35     185       Phoenix
5    Robert   28     177  Philadelphia
6    Daniel   24     182   San Antonio
7   Matthew   33     174     San Diego
8    Andrew   26     180        Dallas
9    Joshua   29     176      San Jose
10     Alex   23     179        Austin

Although because we didn't set the inline parameter as True, we have assign it to a variable because it didn't change the actual DataFrame:

In [39]:
guys.head()

name  age  height qualification         city
0   John   25     175    Bachelor's     New York
1   Mike   30     180      Master's  Los Angeles
2  Chris   22     170    Bachelor's      Chicago
3  David   27     178           PhD      Houston
4  James   35     185      Master's      Phoenix

#### Delete a Row from a DataFrame

In [40]:
guys.drop(index=1, axis=0)

name  age  height qualification          city
0      John   25     175    Bachelor's      New York
2     Chris   22     170    Bachelor's       Chicago
3     David   27     178           PhD       Houston
4     James   35     185      Master's       Phoenix
5    Robert   28     177    Bachelor's  Philadelphia
6    Daniel   24     182      Master's   San Antonio
7   Matthew   33     174           PhD     San Diego
8    Andrew   26     180    Bachelor's        Dallas
9    Joshua   29     176      Master's      San Jose
10     Alex   23     179    Bachelor's        Austin

It deleted Mike's data. We can also delete multiple rows at once:

In [41]:
guys.drop([3, 6])

name  age  height qualification          city
0      John   25     175    Bachelor's      New York
1      Mike   30     180      Master's   Los Angeles
2     Chris   22     170    Bachelor's       Chicago
4     James   35     185      Master's       Phoenix
5    Robert   28     177    Bachelor's  Philadelphia
7   Matthew   33     174           PhD     San Diego
8    Andrew   26     180    Bachelor's        Dallas
9    Joshua   29     176      Master's      San Jose
10     Alex   23     179    Bachelor's        Austin

Here, it deleted David's and Daniel's data. As axis is always 0 by default, we didn't actually have to mension it while deleting rows. Also, we didn't have to use the property name index id we are passing the indices as the first argument.  
Remember that drop doesn't change the actual DataFrame unless the inplace property is True.

#### Rename a Column of a DataFrame

In [42]:
guys.rename(mapper={'name': 'first name', 'qualification': 'education'}, axis=1)

first name  age  height   education          city
0        John   25     175  Bachelor's      New York
1        Mike   30     180    Master's   Los Angeles
2       Chris   22     170  Bachelor's       Chicago
3       David   27     178         PhD       Houston
4       James   35     185    Master's       Phoenix
5      Robert   28     177  Bachelor's  Philadelphia
6      Daniel   24     182    Master's   San Antonio
7     Matthew   33     174         PhD     San Diego
8      Andrew   26     180  Bachelor's        Dallas
9      Joshua   29     176    Master's      San Jose
10       Alex   23     179  Bachelor's        Austin

Here, we also have to set the inplace property as True if we want to change the original DataFrame.

#### Rename a Row of a DataFrame

In [43]:
guys.rename({0: 'zero', 10: 100})

name  age  height qualification          city
zero     John   25     175    Bachelor's      New York
1        Mike   30     180      Master's   Los Angeles
2       Chris   22     170    Bachelor's       Chicago
3       David   27     178           PhD       Houston
4       James   35     185      Master's       Phoenix
5      Robert   28     177    Bachelor's  Philadelphia
6      Daniel   24     182      Master's   San Antonio
7     Matthew   33     174           PhD     San Diego
8      Andrew   26     180    Bachelor's        Dallas
9      Joshua   29     176      Master's      San Jose
100      Alex   23     179    Bachelor's        Austin

Here, we got the modified indices. mapper property name is not necessary if the dict is the first argument to be passed.  
To learn more about the inplace property, go to ...

### Indexing and Slicing

In [44]:
guys

name  age  height qualification          city
0      John   25     175    Bachelor's      New York
1      Mike   30     180      Master's   Los Angeles
2     Chris   22     170    Bachelor's       Chicago
3     David   27     178           PhD       Houston
4     James   35     185      Master's       Phoenix
5    Robert   28     177    Bachelor's  Philadelphia
6    Daniel   24     182      Master's   San Antonio
7   Matthew   33     174           PhD     San Diego
8    Andrew   26     180    Bachelor's        Dallas
9    Joshua   29     176      Master's      San Jose
10     Alex   23     179    Bachelor's        Austin

#### Access Columns of a DataFrame

In [45]:
guys['name']

0        John
1        Mike
2       Chris
3       David
4       James
5      Robert
6      Daniel
7     Matthew
8      Andrew
9      Joshua
10       Alex
Name: name, dtype: object

Here we got the indices and the elements the name column. We can also access multiple columns:

In [46]:
guys[['name', 'age']]

name  age
0      John   25
1      Mike   30
2     Chris   22
3     David   27
4     James   35
5    Robert   28
6    Daniel   24
7   Matthew   33
8    Andrew   26
9    Joshua   29
10     Alex   23

Here we got the names and the ages of the guys with their indices.  
The [] operator, however, provides limited functionality. Even basic operations like selecting rows, slicing DataFrames and selecting individual elements are quite tricky using the [] operator only.  
So we use the .loc and .iloc properties for indexing and slicing DataFrames. They provide much more flexibility compared to the [] operator.

#### Indexing Using the loc Property

##### Access a row

In [47]:
guys.loc[2]

name                  Chris
age                      22
height                  170
qualification    Bachelor's
city                Chicago
Name: 2, dtype: object

##### Access multiple rows

In [48]:
guys.loc[[2, 4, 5]]

name  age  height qualification          city
2   Chris   22     170    Bachelor's       Chicago
4   James   35     185      Master's       Phoenix
5  Robert   28     177    Bachelor's  Philadelphia

##### Access a column

In [49]:
guys.loc[:, 'name']

0        John
1        Mike
2       Chris
3       David
4       James
5      Robert
6      Daniel
7     Matthew
8      Andrew
9      Joshua
10       Alex
Name: name, dtype: object

##### Access multiple columns

In [50]:
guys.loc[:, ['name', 'city']]

name          city
0      John      New York
1      Mike   Los Angeles
2     Chris       Chicago
3     David       Houston
4     James       Phoenix
5    Robert  Philadelphia
6    Daniel   San Antonio
7   Matthew     San Diego
8    Andrew        Dallas
9    Joshua      San Jose
10     Alex        Austin

##### Access a specific cell (row and column location)

In [51]:
guys.loc[2, 'name']

'Chris'

##### Access specific cells

In [52]:
guys.loc[[2, 4, 5], 'name']

2     Chris
4     James
5    Robert
Name: name, dtype: object

In [53]:
guys.loc[2, ['name', 'city']]

name      Chris
city    Chicago
Name: 2, dtype: object

In [54]:
guys.loc[[2, 4, 5], ['name', 'city']]

name          city
2   Chris       Chicago
4   James       Phoenix
5  Robert  Philadelphia

#### Slicing Using the loc Property

##### Row Slicing

In [55]:
guys.loc[2:5]

name  age  height qualification          city
2   Chris   22     170    Bachelor's       Chicago
3   David   27     178           PhD       Houston
4   James   35     185      Master's       Phoenix
5  Robert   28     177    Bachelor's  Philadelphia

Here we got rows from index 2 to index 5.

##### Column Slicing

In [56]:
guys.loc[:, 'name':'height']

name  age  height
0      John   25     175
1      Mike   30     180
2     Chris   22     170
3     David   27     178
4     James   35     185
5    Robert   28     177
6    Daniel   24     182
7   Matthew   33     174
8    Andrew   26     180
9    Joshua   29     176
10     Alex   23     179

Here we got columns from name to height.

##### Row and Column Slicing (Together)

In [57]:
guys.loc[2:5, 'name':'height']

name  age  height
2   Chris   22     170
3   David   27     178
4   James   35     185
5  Robert   28     177

Here we got rows from index 2 to 5 and columns from name to height.

#### Boolean Indexing

We can use the boolean indexing to set conditions and filter the data:

In [58]:
guys.loc[guys['age'] > 27]

name  age  height qualification          city
1     Mike   30     180      Master's   Los Angeles
4    James   35     185      Master's       Phoenix
5   Robert   28     177    Bachelor's  Philadelphia
7  Matthew   33     174           PhD     San Diego
9   Joshua   29     176      Master's      San Jose

#### loc vs iloc

The main differences between .loc and .iloc are as follows:

| Basis                | loc                                   | iloc                                  |
|----------------------|---------------------------------------|---------------------------------------|
| Indexing             | Label-based indexing                  | Integer-based indexing                |
| Endpoint             | Included                              | Not included                          |
| Boolean Indexing     | Supported                             | Not supported                         |
    

#### to_string() Function

When we want to extract data from a DataFrame as a string, we can use this function:

In [59]:
guys.to_string()

"       name  age  height qualification          city\n0      John   25     175    Bachelor's      New York\n1      Mike   30     180      Master's   Los Angeles\n2     Chris   22     170    Bachelor's       Chicago\n3     David   27     178           PhD       Houston\n4     James   35     185      Master's       Phoenix\n5    Robert   28     177    Bachelor's  Philadelphia\n6    Daniel   24     182      Master's   San Antonio\n7   Matthew   33     174           PhD     San Diego\n8    Andrew   26     180    Bachelor's        Dallas\n9    Joshua   29     176      Master's      San Jose\n10     Alex   23     179    Bachelor's        Austin"

We can also drop the index numbers like this:

In [60]:
guys.to_string(index=False)

"   name  age  height qualification         city\n   John   25     175    Bachelor's     New York\n   Mike   30     180      Master's  Los Angeles\n  Chris   22     170    Bachelor's      Chicago\n  David   27     178           PhD      Houston\n  James   35     185      Master's      Phoenix\n Robert   28     177    Bachelor's Philadelphia\n Daniel   24     182      Master's  San Antonio\nMatthew   33     174           PhD    San Diego\n Andrew   26     180    Bachelor's       Dallas\n Joshua   29     176      Master's     San Jose\n   Alex   23     179    Bachelor's       Austin"

We can also use loc and iloc with it, for example:

In [61]:
guys.loc[2:5, 'name':'height'].to_string(index=False)

'  name  age  height\n Chris   22     170\n David   27     178\n James   35     185\nRobert   28     177'

#### query() Function

This method allows you to select data using a more SQL-like syntax:

In [62]:
guys.query('age > 27')

name  age  height qualification          city
1     Mike   30     180      Master's   Los Angeles
4    James   35     185      Master's       Phoenix
5   Robert   28     177    Bachelor's  Philadelphia
7  Matthew   33     174           PhD     San Diego
9   Joshua   29     176      Master's      San Jose

#### isin() Function

It is used to filter rows based on a list of values. For example:

In [63]:
guys.loc[guys['name'].isin(['Mike', 'James'])]

name  age  height qualification         city
1   Mike   30     180      Master's  Los Angeles
4  James   35     185      Master's      Phoenix

#### Multi-Index

**Multi-Index:** It is a hierarchical indexing structure that allows to represent and work with higher-dimensional data efficiently.  
While a typical index refers to a single column, a MultiIndex contains multiple levels of indices.

let's create another DataFrame for this:

In [64]:
cities = pd.DataFrame({
    "city": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose"],
    "state": ["New York", "California", "Illinois", "Texas", "Arizona", "Pennsylvania", "Texas", "California", "Texas", "California"],
    "establishment year": [1624, 1781, 1837, 1837, 1868, 1682, 1718, 1769, 1841, 1777]
})
cities

city         state  establishment year
0      New York      New York                1624
1   Los Angeles    California                1781
2       Chicago      Illinois                1837
3       Houston         Texas                1837
4       Phoenix       Arizona                1868
5  Philadelphia  Pennsylvania                1682
6   San Antonio         Texas                1718
7     San Diego    California                1769
8        Dallas         Texas                1841
9      San Jose    California                1777

Here, we can see that the state data is repeated for some cities. To avoid this data redundancy, we can use multiindex. But first, we should sort this DataFrame data based on the state column:

In [65]:
cities.sort_values('state', inplace=True)
cities

city         state  establishment year
4       Phoenix       Arizona                1868
1   Los Angeles    California                1781
7     San Diego    California                1769
9      San Jose    California                1777
2       Chicago      Illinois                1837
0      New York      New York                1624
5  Philadelphia  Pennsylvania                1682
3       Houston         Texas                1837
6   San Antonio         Texas                1718
8        Dallas         Texas                1841

As we can see, it sorted out the data based on the state column. Now we can set a multi-index:

In [66]:
cities.set_index(['state', 'city'], inplace=True)
cities

establishment year
state        city                            
Arizona      Phoenix                     1868
California   Los Angeles                 1781
             San Diego                   1769
             San Jose                    1777
Illinois     Chicago                     1837
New York     New York                    1624
Pennsylvania Philadelphia                1682
Texas        Houston                     1837
             San Antonio                 1718
             Dallas                      1841

Now the state and city values are indices. State is the parent index of city. Here is an illustration:

<img src="https://atharvsuryavanshi.github.io/Diagram-Manager/images/pandas-multi-index-example.png" alt="multi-index-example.png" width="1000">

(If the image isn't visible then click here: [Pandas Multi-Index](https://atharvsuryavanshi.github.io/Diagram-Manager/images/pandas-multi-index-example.png))

To acces the data we have to use them like this:

In [67]:
cities.loc['California']

establishment year
city                           
Los Angeles                1781
San Diego                  1769
San Jose                   1777

And here we got all the 3 cities which are in the state of California.

In [68]:
cities.loc[('California', 'San Diego')]

establishment year    1769
Name: (California, San Diego), dtype: int64

And here we got all the values (there was just the establishment date) under the California and San Diego indices**.  
**Note:** We need to provide the full hierarchical index in the form of a tuple in order to access a particular row.  
We can also make a DataFrame with multi-index directly although it looks kinda complicated:

In [69]:
pd.DataFrame({
    "establishment year": [1781, 1769, 1777, 1837, 1624, 1682, 1837, 1718, 1841, 1868]
}, index=pd.MultiIndex.from_arrays([
    ["California", "California", "California", "Illinois", "New York", "Pennsylvania", "Texas", "Texas", "Texas", "Arizona"],
    ["Los Angeles", "San Diego", "San Jose", "Chicago", "New York", "Philadelphia", "Houston", "San Antonio", "Dallas", "Phoenix"]
], names=['state', 'city']))

establishment year
state        city                            
California   Los Angeles                 1781
             San Diego                   1769
             San Jose                    1777
Illinois     Chicago                     1837
New York     New York                    1624
Pennsylvania Philadelphia                1682
Texas        Houston                     1837
             San Antonio                 1718
             Dallas                      1841
Arizona      Phoenix                     1868

**Note:** While passing an array of multi-indices to the from_arrays() function, keep the order from parent indices to child indices. Also, sort the data first according to the respective parent indices.

### Reshape

Reshaping data refers to the process of converting a DataFrame from one format to another for better data visualization and analysis.  
Pandas provides multiple methods like pivot(), pivot_table(), stack(), unstack() and melt() to reshape data. We can choose the method based on our analysis requirement.  
Let's create another DataFrame for this:

In [70]:
boys = pd.DataFrame({
    "name": ["Aarav", "Vivaan", "Aditya", "Vihaan", "Arjun", "Sai", "Rishi", "Aryan", "Dhruv", "Kabir"],
    "dob": ["2001-05-14", "2003-08-21", "2000-12-05", "2002-07-18", "1999-11-11", "2005-03-30", "2004-09-25", "2001-06-01", "2003-10-12", "2004-04-17"],
    "age": [23, 20, 24, 21, 25, 19, 20, 23, 20, 19],
    "city": ["Mumbai", "Delhi", "Bangalore", "Mumbai", "Hyderabad", "Pune", "Kolkata", "Delhi", "Bangalore", "Mumbai"]
})
boys

name         dob  age       city
0   Aarav  2001-05-14   23     Mumbai
1  Vivaan  2003-08-21   20      Delhi
2  Aditya  2000-12-05   24  Bangalore
3  Vihaan  2002-07-18   21     Mumbai
4   Arjun  1999-11-11   25  Hyderabad
5     Sai  2005-03-30   19       Pune
6   Rishi  2004-09-25   20    Kolkata
7   Aryan  2001-06-01   23      Delhi
8   Dhruv  2003-10-12   20  Bangalore
9   Kabir  2004-04-17   19     Mumbai

#### Reshape Data using pivot()

This function reshapes data based on column values. It takes simple column-wise data as input, and groups the entries into a two-dimensional table.

In [71]:
boys.pivot(index='city', columns='age', values='name')

age           19      20      21     23      24     25
city                                                  
Bangalore    NaN   Dhruv     NaN    NaN  Aditya    NaN
Delhi        NaN  Vivaan     NaN  Aryan     NaN    NaN
Hyderabad    NaN     NaN     NaN    NaN     NaN  Arjun
Kolkata      NaN   Rishi     NaN    NaN     NaN    NaN
Mumbai     Kabir     NaN  Vihaan  Aarav     NaN    NaN
Pune         Sai     NaN     NaN    NaN     NaN    NaN

Here, we got a view in which the columns are the ages and the indices are the cities. In this view, the values are the names of the boys and NaN where any name doesn't fit.
- index specifies the column to be used as the index for the pivoted DataFrame.
- columns specifies the column whose unique values will become the new column headers.
- values specifies the column containing the values to be placed in the new columns.

<img src="https://atharvsuryavanshi.github.io/Diagram-Manager/images/pandas-pivot-example.png" alt="pandas-pivot-example.png" width="1000">

(If the image isn't visible then click here: [Pandas Pivot Function](https://atharvsuryavanshi.github.io/Diagram-Manager/images/pandas-pivot-example.png))

#### Reshape Data using pivot_table()

It is a way for reshaping and summarizing data in a DataFrame. It allows us to create a pivot table that aggregates and summarizes data based on the specified index, columns, and aggregation functions.

In [72]:
boys.pivot_table(index='city', values='age', aggfunc='mean')

age
city           
Bangalore  22.0
Delhi      21.5
Hyderabad  25.0
Kolkata    20.0
Mumbai     21.0
Pune       19.0

Here we got a view in which the rows are the cities and the column is age which is showing mean ages for each city.
- index: the column to use as row labels.
- columns: the column that will be reshaped as columns.
- values: the column(s) to use for the new DataFrame's values.
- aggfunc: the function to use for aggregation, defaulting to 'mean'.
- fill_value: value to replace missing values with.
- dropna: whether to exclude the columns whose entries are all NaN.

**Difference between pivot() and pivot_table():** The pivot() and pivot_table() functions perform similar operations but with few key differences:

| Basis                | pivot()                                 | pivot_table()                               |
|----------------------|-----------------------------------------|---------------------------------------------|
| Aggregation          | Does not allow aggregation of data.     | Allows aggregation. (sum, mean, count, etc.)|
| Duplicate Index      | Cannot handle duplicate index values.   | Can handle duplicate index values.          |
| MultiIndex           | Only accepts a single-level index.      | Accepts multi-level index for complex data. |

#### Reshape Data using stack() and unstack()

We can also use the stack() and unstack() to reshape data:
- stack() is used to pivot a level of the column labels, transforming them into innermost row index levels.
- unstack() is used to pivot a level of the row index, transforming it into an outermost column level

In [73]:
boys.set_index('age').stack()

age      
23   name         Aarav
     dob     2001-05-14
     city        Mumbai
20   name        Vivaan
     dob     2003-08-21
     city         Delhi
24   name        Aditya
     dob     2000-12-05
     city     Bangalore
21   name        Vihaan
     dob     2002-07-18
     city        Mumbai
25   name         Arjun
     dob     1999-11-11
     city     Hyderabad
19   name           Sai
     dob     2005-03-30
     city          Pune
20   name         Rishi
     dob     2004-09-25
     city       Kolkata
23   name         Aryan
     dob     2001-06-01
     city         Delhi
20   name         Dhruv
     dob     2003-10-12
     city     Bangalore
19   name         Kabir
     dob     2004-04-17
     city        Mumbai
dtype: object

In [74]:
boys.set_index('name').unstack()

      name  
dob   Aarav     2001-05-14
      Vivaan    2003-08-21
      Aditya    2000-12-05
      Vihaan    2002-07-18
      Arjun     1999-11-11
      Sai       2005-03-30
      Rishi     2004-09-25
      Aryan     2001-06-01
      Dhruv     2003-10-12
      Kabir     2004-04-17
age   Aarav             23
      Vivaan            20
      Aditya            24
      Vihaan            21
      Arjun             25
      Sai               19
      Rishi             20
      Aryan             23
      Dhruv             20
      Kabir             19
city  Aarav         Mumbai
      Vivaan         Delhi
      Aditya     Bangalore
      Vihaan        Mumbai
      Arjun      Hyderabad
      Sai             Pune
      Rishi        Kolkata
      Aryan          Delhi
      Dhruv      Bangalore
      Kabir         Mumbai
dtype: object

**Name:** Columns with duplicate values are not supported with unstack(). For example: age column.

#### Reshape Data using melt()

It transforms a DataFrame from a wide format to a long format.  
Let's make another DataFrame for showing this:

In [75]:
students = pd.DataFrame({
    "name": ["Rohan", "Soham", "Tanmay"],
    "marathi": [85, 78, 92],
    "maths": [95, 88, 84],
    "science": [88, 91, 90],
    "history": [80, 85, 78]
})
students

name  marathi  maths  science  history
0   Rohan       85     95       88       80
1   Soham       78     88       91       85
2  Tanmay       92     84       90       78

Now, let's use the melt() method:

In [76]:
pd.melt(students, id_vars='name', var_name='subject', value_name='marks')

name  subject  marks
0    Rohan  marathi     85
1    Soham  marathi     78
2   Tanmay  marathi     92
3    Rohan    maths     95
4    Soham    maths     88
5   Tanmay    maths     84
6    Rohan  science     88
7    Soham  science     91
8   Tanmay  science     90
9    Rohan  history     80
10   Soham  history     85
11  Tanmay  history     78

So, we used the melt() function to transform the DataFrame df from a wide format to a long format.
- id_vars specifies the column that we want to keep unchanged.
- var_name specifies the name for the new column that will hold the variable names.
- value_name specifies the name for the new column that will hold the values.

### Handling Duplicate Values

Pandas provides several methods to find and remove duplicate entries in DataFrames.

In [77]:
boys

name         dob  age       city
0   Aarav  2001-05-14   23     Mumbai
1  Vivaan  2003-08-21   20      Delhi
2  Aditya  2000-12-05   24  Bangalore
3  Vihaan  2002-07-18   21     Mumbai
4   Arjun  1999-11-11   25  Hyderabad
5     Sai  2005-03-30   19       Pune
6   Rishi  2004-09-25   20    Kolkata
7   Aryan  2001-06-01   23      Delhi
8   Dhruv  2003-10-12   20  Bangalore
9   Kabir  2004-04-17   19     Mumbai

#### Find Duplicate Entries

We can find duplicate entries in a DataFrame using the duplicated() method. It returns True if a row is duplicated and returns False otherwise.

In [78]:
boys.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

By default, duplicated() considers all columns. There was no row with all the duplicate values and that's why it returned False for all.  
To find duplicates based on certain columns, we can pass them as a list to the duplicated() function:

In [79]:
boys.duplicated(subset='age')

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool

Because the age column has duplicate values, we got True for indices 6 to 9. We can also check for multiple columns at once:

In [80]:
boys.duplicated(subset=['age', 'city'])

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

That means there is no row in the DataFrame which has same age and city values.

#### Remove Duplicate Entries

We can remove duplicate entries in using the drop_duplicates() method.

In [81]:
boys.drop_duplicates(subset='age')

name         dob  age       city
0   Aarav  2001-05-14   23     Mumbai
1  Vivaan  2003-08-21   20      Delhi
2  Aditya  2000-12-05   24  Bangalore
3  Vihaan  2002-07-18   21     Mumbai
4   Arjun  1999-11-11   25  Hyderabad
5     Sai  2005-03-30   19       Pune

Here the duplicate rows we had got before are removed. Although, it didn't change the original DataFrame and to do that we could set the inplace property as True. To keep last entry instead of the first entry, we can do this:

In [82]:
boys.drop_duplicates(subset='age', keep='last')

name         dob  age       city
2  Aditya  2000-12-05   24  Bangalore
3  Vihaan  2002-07-18   21     Mumbai
4   Arjun  1999-11-11   25  Hyderabad
7   Aryan  2001-06-01   23      Delhi
8   Dhruv  2003-10-12   20  Bangalore
9   Kabir  2004-04-17   19     Mumbai

Here, it removed the rows at indices 0, 1, 5 and 6. That means it kept the last occurances instead of the first.

## Data Import and Export

Let's see our data first:

In [83]:
boys

name         dob  age       city
0   Aarav  2001-05-14   23     Mumbai
1  Vivaan  2003-08-21   20      Delhi
2  Aditya  2000-12-05   24  Bangalore
3  Vihaan  2002-07-18   21     Mumbai
4   Arjun  1999-11-11   25  Hyderabad
5     Sai  2005-03-30   19       Pune
6   Rishi  2004-09-25   20    Kolkata
7   Aryan  2001-06-01   23      Delhi
8   Dhruv  2003-10-12   20  Bangalore
9   Kabir  2004-04-17   19     Mumbai

### Reading and Writing Data to a CSV File

In [84]:
boys.to_csv('boys.csv', index=False)

These are some commonly used arguments of the to_csv() function. All of them are optional except path_or_buf:
- **path_or_buf:** represents the path or buffer object where the DataFrame will be saved as a CSV file.
- **sep:** specifies the delimiter to be used in the output CSV file.
- **header:** indicates whether to include the header row in the output CSV file.
- **index:** determines whether to include the index column in the output CSV file.
- **mode:** specifies the mode in which the output file will be opened.
- **encoding:** sets the character encoding to be used when writing the CSV file.
- **quoting:** determines the quoting behavior for fields that contain special characters.
- **line_terminator:** specifies the character sequence used to terminate lines in the output CSV file.

In [85]:
pd.read_csv('boys.csv')

name         dob  age       city
0   Aarav  2001-05-14   23     Mumbai
1  Vivaan  2003-08-21   20      Delhi
2  Aditya  2000-12-05   24  Bangalore
3  Vihaan  2002-07-18   21     Mumbai
4   Arjun  1999-11-11   25  Hyderabad
5     Sai  2005-03-30   19       Pune
6   Rishi  2004-09-25   20    Kolkata
7   Aryan  2001-06-01   23      Delhi
8   Dhruv  2003-10-12   20  Bangalore
9   Kabir  2004-04-17   19     Mumbai

If the filename isn't provided then it returns a CSV string:

In [86]:
boys.to_csv(index=False)

'name,dob,age,city\r\nAarav,2001-05-14,23,Mumbai\r\nVivaan,2003-08-21,20,Delhi\r\nAditya,2000-12-05,24,Bangalore\r\nVihaan,2002-07-18,21,Mumbai\r\nArjun,1999-11-11,25,Hyderabad\r\nSai,2005-03-30,19,Pune\r\nRishi,2004-09-25,20,Kolkata\r\nAryan,2001-06-01,23,Delhi\r\nDhruv,2003-10-12,20,Bangalore\r\nKabir,2004-04-17,19,Mumbai\r\n'

These are some commonly used arguments of the read_csv() function. All of them are optional except filepath_or_buffer:
- **filepath_or_buffer:** represents the path or buffer object containing the CSV data to be read.
- **sep** specifies the delimiter used in the CSV file.
- **header:** indicates the row number to be used as the header or column names.
- **names:** a list of column names to assign to the DataFrame.
- **index_col:** specifies the column to be used as the index of the DataFrame.
- **usecols:** a list of columns to be read and included in the DataFrame.
- **skiprows:** used to skip specific rows while reading the CSV file.
- **nrows:** sets the maximum number of rows to be read from the CSV file.
- **skipinitialspace:** determines whether to skip any whitespace after the delimiter in each field.

### Reading and Writing Data to an Excel Sheet

In [87]:
boys.to_excel('boys.xlsx', index=False)

Parameters:
- **excel_writer:** specifies the file path or existing ExcelWriter.
- **sheet_name:** specifies the sheet name or names.
- **na_rep:** specifies the representation for missing data.
- **float_format:** specifies the format for floating-point numbers.
- **columns:** specifies the columns to write.
- **header:** specifies whether to write the column headers.
- **index:** specifies whether to write the DataFrame’s index.
- **index_label:** specifies the column label for the index column(s).
- **startrow:** specifies the upper left cell row to dump data frame.
- **startcol:** specifies the upper left cell column to dump data frame.
- **engine:** specifies the write engine to use.
- **merge_cells:** specifies whether to merge cells.
- **encoding:** specifies the encoding of the resulting file.
- **inf_rep:** specifies the representation for infinity.
- **verbose:** specifies whether to show output.
- **freeze_panes:** specifies the one- or two-dimensional array-like to freeze.

In [88]:
pd.read_excel('boys.xlsx')

name         dob  age       city
0   Aarav  2001-05-14   23     Mumbai
1  Vivaan  2003-08-21   20      Delhi
2  Aditya  2000-12-05   24  Bangalore
3  Vihaan  2002-07-18   21     Mumbai
4   Arjun  1999-11-11   25  Hyderabad
5     Sai  2005-03-30   19       Pune
6   Rishi  2004-09-25   20    Kolkata
7   Aryan  2001-06-01   23      Delhi
8   Dhruv  2003-10-12   20  Bangalore
9   Kabir  2004-04-17   19     Mumbai

Parameters:
- **io:** specifies the file path, URL, or file-like object.
- **sheet_name:** specifies the sheet name, sheet number, or list of sheet names/numbers.
- **header:** specifies the row number(s) to use as the column names.
- **names:** specifies the column names to use.
- **index_col:** specifies the column(s) to set as the index.
- **usecols:** specifies the columns to parse.
- **squeeze:** specifies whether to return a Series when reading only one column.
- **dtype:** specifies the data type for data or columns.
- **engine:** specifies the write engine to use.
- **converters:** specifies the functions for converting values in certain columns.
- **true_values:** specifies the values to consider as True.
- **false_values:** specifies the values to consider as False.
- **skiprows:** specifies the rows to skip at the beginning.
- **nrows:** specifies the number of rows to read.
- **na_values:** specifies the additional strings to recognize as NA/NaN.
- **parse_dates:** specifies the columns to parse as dates.
- **date_parser:** specifies the function to use for parsing dates.
- **thousands:** specifies the character to recognize as thousands separator.
- **comment:** specifies the character to recognize as a comment indicator.
- **skipfooter:** specifies the number of lines to skip at the end.
- **convert_float:** specifies whether to convert integral floats to int.
- **mangle_dupe_cols:** specifies whether to mangle duplicate columns.

### Reading and Writing Data to a SQL File

For SQL, we need to setup some things. First we have to install SQLAlchemy package: `pip install sqlalchemy`.  
Then we have to create an engine. After that we can save and read data from an SQL file.

In [89]:
from sqlalchemy import create_engine
engine = create_engine('sqlite:///boys.db')
boys.to_sql('boys', con=engine, if_exists='replace', index=False)

10

Parameters:
- **name:** specifies the name of the SQL table.
- **con:** specifies the connection object to the database.
- **schema:** specifies the schema in which the table will be created.
- **if_exists:** specifies what to do if the table already exists ('fail', 'replace', 'append').
- **index:** specifies whether to write the DataFrame's index as a column.
- **index_label:** specifies the column label for the index column(s).
- **chunksize:** specifies the number of rows to write at a time.
- **dtype:** specifies the data types for the columns.
- **method:** specifies the method to use for inserting data into the SQL table.

In [90]:
pd.read_sql('boys', con=engine)

name         dob  age       city
0   Aarav  2001-05-14   23     Mumbai
1  Vivaan  2003-08-21   20      Delhi
2  Aditya  2000-12-05   24  Bangalore
3  Vihaan  2002-07-18   21     Mumbai
4   Arjun  1999-11-11   25  Hyderabad
5     Sai  2005-03-30   19       Pune
6   Rishi  2004-09-25   20    Kolkata
7   Aryan  2001-06-01   23      Delhi
8   Dhruv  2003-10-12   20  Bangalore
9   Kabir  2004-04-17   19     Mumbai

Parameters:
- **sql:** specifies the SQL query or the table name to read from the database.
- **con:** specifies the connection object to the database.
- **index_col:** specifies the column(s) to set as the index of the DataFrame.
- **coerce_float:** specifies whether to attempt to convert values to floats.
- **params:** specifies the parameters to pass to the SQL query.
- **parse_dates:** specifies the columns to parse as dates.
- **columns:** specifies the columns to read from the SQL table.
- **chunksize:** specifies the number of rows to include in each chunk when reading the data.

### Reading and Writing Data to a JSON File

In [91]:
boys.to_json('boys.json', index=False)

These are some commonly used arguments of the to_json() function:
- **path_or_buf:** specifies the file path or buffer where the JSON string is written.
- **orient:** specifies the format of the JSON string.
- **lines:** specifies whether the resulting JSON string should be in a line-separated format.
- **compression:** specifies the compression algorithm for file output.
- **index:** specifies whether to include the DataFrame's index in the JSON string.

In [92]:
pd.read_json('boys.json')

name         dob  age       city
0   Aarav  2001-05-14   23     Mumbai
1  Vivaan  2003-08-21   20      Delhi
2  Aditya  2000-12-05   24  Bangalore
3  Vihaan  2002-07-18   21     Mumbai
4   Arjun  1999-11-11   25  Hyderabad
5     Sai  2005-03-30   19       Pune
6   Rishi  2004-09-25   20    Kolkata
7   Aryan  2001-06-01   23      Delhi
8   Dhruv  2003-10-12   20  Bangalore
9   Kabir  2004-04-17   19     Mumbai

If the filename isn't provided then it returns a JSON string:

In [93]:
boys.to_json(index=False)

'{"name":{"0":"Aarav","1":"Vivaan","2":"Aditya","3":"Vihaan","4":"Arjun","5":"Sai","6":"Rishi","7":"Aryan","8":"Dhruv","9":"Kabir"},"dob":{"0":"2001-05-14","1":"2003-08-21","2":"2000-12-05","3":"2002-07-18","4":"1999-11-11","5":"2005-03-30","6":"2004-09-25","7":"2001-06-01","8":"2003-10-12","9":"2004-04-17"},"age":{"0":23,"1":20,"2":24,"3":21,"4":25,"5":19,"6":20,"7":23,"8":20,"9":19},"city":{"0":"Mumbai","1":"Delhi","2":"Bangalore","3":"Mumbai","4":"Hyderabad","5":"Pune","6":"Kolkata","7":"Delhi","8":"Bangalore","9":"Mumbai"}}'

These are some commonly used arguments of the read_json() function:
- **filepath_or_buffer:** specifies the path or URL to the JSON file or a file-like object containing the JSON data.
- **orient:** specifies the orientation of the JSON file.
- **typ:** indicates the type of expected output.
- **precise_float:** specifies whether to parse floats precisely.
- **encoding:** specifies the encoding to be used when reading the JSON file.
- **lines:** controls various aspects of the data reading process.

### Some Additional Methods

#### Reading and Writing Data to an HTML File

In [94]:
boys.to_html('boys.html', index=False)

In [95]:
pd.read_html('boys.html')

[     name         dob  age       city
 0   Aarav  2001-05-14   23     Mumbai
 1  Vivaan  2003-08-21   20      Delhi
 2  Aditya  2000-12-05   24  Bangalore
 3  Vihaan  2002-07-18   21     Mumbai
 4   Arjun  1999-11-11   25  Hyderabad
 5     Sai  2005-03-30   19       Pune
 6   Rishi  2004-09-25   20    Kolkata
 7   Aryan  2001-06-01   23      Delhi
 8   Dhruv  2003-10-12   20  Bangalore
 9   Kabir  2004-04-17   19     Mumbai]

#### Reading and Writing Data to an XML File

In [96]:
boys.to_xml('boys.xml', index=False)

In [97]:
pd.read_xml('boys.xml')

name         dob  age       city
0   Aarav  2001-05-14   23     Mumbai
1  Vivaan  2003-08-21   20      Delhi
2  Aditya  2000-12-05   24  Bangalore
3  Vihaan  2002-07-18   21     Mumbai
4   Arjun  1999-11-11   25  Hyderabad
5     Sai  2005-03-30   19       Pune
6   Rishi  2004-09-25   20    Kolkata
7   Aryan  2001-06-01   23      Delhi
8   Dhruv  2003-10-12   20  Bangalore
9   Kabir  2004-04-17   19     Mumbai

**Note:** For both to_html() and to_xml() if the filename isn't provided then they also return strings.

In [98]:
# Additional Functionalities:
# https://www.programiz.com/python-programming/pandas/merge
# https://www.programiz.com/python-programming/pandas/join
# https://www.programiz.com/python-programming/pandas/concat

## Data Cleaning

Data cleaning means fixing and organizing messy data. Pandas offers a wide range of tools and functions to help us clean and preprocess our data effectively.  
Data cleaning often involves:
- Dropping irrelevant columns.
- Renaming column names to meaningful names.
- Making data values consistent.
- Replacing or filling in missing values.

### Missing Values

Missing values, often represented as NaN (Not a Number), can cause problems during data processing and analysis. These gaps in data can lead to incorrect analysis and misleading conclusions.  
Let's first create a DataFrame with many missing values:

In [99]:
reelers = pd.DataFrame({
    "name": ["Emma Watson", "John Doe", None, "Michael Johnson", None, "Ethan Miller", "Olivia Davis", None, "Ava Taylor", None],
    "username": ["emma_watson01", "john.doe_02", "a.smith_03", "michael123", "sophia.brown05", "e.miller06", "olivia-davis07", "william_w", "avataylor", "dmartinez10"],
    "date of joining": ["2023-02-14", "2023-01-21", None, "2023-03-15", None, "2023-04-20", "2023-06-18", None, "2023-07-25", None],
    "number of reels": [5, 20, None, 15, None, 25, 30, None, 22, None],
    "followers": [10000, 15000, None, 20000, None, 25000, 30000, None, 35000, None]
})
reelers

name        username date of joining  number of reels  followers
0      Emma Watson   emma_watson01      2023-02-14              5.0    10000.0
1         John Doe     john.doe_02      2023-01-21             20.0    15000.0
2             None      a.smith_03            None              NaN        NaN
3  Michael Johnson      michael123      2023-03-15             15.0    20000.0
4             None  sophia.brown05            None              NaN        NaN
5     Ethan Miller      e.miller06      2023-04-20             25.0    25000.0
6     Olivia Davis  olivia-davis07      2023-06-18             30.0    30000.0
7             None       william_w            None              NaN        NaN
8       Ava Taylor       avataylor      2023-07-25             22.0    35000.0
9             None     dmartinez10            None              NaN        NaN

#### Drop Rows With Missing Values

We can drop rows with missing values using the dropna() function:

In [100]:
reelers.dropna()

name        username date of joining  number of reels  followers
0      Emma Watson   emma_watson01      2023-02-14              5.0    10000.0
1         John Doe     john.doe_02      2023-01-21             20.0    15000.0
3  Michael Johnson      michael123      2023-03-15             15.0    20000.0
5     Ethan Miller      e.miller06      2023-04-20             25.0    25000.0
6     Olivia Davis  olivia-davis07      2023-06-18             30.0    30000.0
8       Ava Taylor       avataylor      2023-07-25             22.0    35000.0

Here, dropna() dropped all the rows which have missing values. We can also do this for columns by setting the axis values as 1:

In [101]:
reelers.dropna(axis=1)

username
0   emma_watson01
1     john.doe_02
2      a.smith_03
3      michael123
4  sophia.brown05
5      e.miller06
6  olivia-davis07
7       william_w
8       avataylor
9     dmartinez10

Becasue there is only the username column with no missing values, we got only that column.

#### Fill Missing Values

To fill the missing values in Pandas, we use the fillna() function.

In [102]:
reelers.fillna('-')

name        username date of joining number of reels followers
0      Emma Watson   emma_watson01      2023-02-14             5.0   10000.0
1         John Doe     john.doe_02      2023-01-21            20.0   15000.0
2                -      a.smith_03               -               -         -
3  Michael Johnson      michael123      2023-03-15            15.0   20000.0
4                -  sophia.brown05               -               -         -
5     Ethan Miller      e.miller06      2023-04-20            25.0   25000.0
6     Olivia Davis  olivia-davis07      2023-06-18            30.0   30000.0
7                -       william_w               -               -         -
8       Ava Taylor       avataylor      2023-07-25            22.0   35000.0
9                -     dmartinez10               -               -         -

So, we replaced all the missing values with an hyphen. We could set inplace property as True to change the original DataFrame.

#### Use Aggregate Functions to Fill Missing Values

In [103]:
reelers_nonstring = reelers.loc[:, ['number of reels', 'followers']]
reelers_nonstring.fillna(reelers_nonstring.mean())

number of reels  followers
0              5.0    10000.0
1             20.0    15000.0
2             19.5    22500.0
3             15.0    20000.0
4             19.5    22500.0
5             25.0    25000.0
6             30.0    30000.0
7             19.5    22500.0
8             22.0    35000.0
9             19.5    22500.0

Because the means for the number of reels and the followers columns are 19.5 and 22500 respectively, the function filled them at the correct places.  
**Note:** We used a numbers only DataFrame here because mean() method doesn't work on strings. That's why we selected nonstring columns only.

### Handling Wrong Format

In a real world scenario, data are taken from various sources which causes inconsistencies in format of the data. With Pandas, we can handle such issues by converting all the values in a column to a specific format.

#### Convert Data to a Format

Let's take a Series example:

In [104]:
temperatures = pd.Series([10, '22.2', 30.5, '14', 23, 43.1])
temperatures

0      10
1    22.2
2    30.5
3      14
4      23
5    43.1
dtype: object

Here, the temperatures have different types, let's convert all of them into float dtype:

In [105]:
temperatures.astype('float')

0    10.0
1    22.2
2    30.5
3    14.0
4    23.0
5    43.1
dtype: float64

Now, all of the values have float64 dtype. We can perform similar operations on DataFrames too.

#### Handling Mixed Date Formats

Dates can be represented in various formats such as mm-dd-yyyy, dd-mm-yyyy, yyyy-mm-dd etc. Also, different separators such as /, -, . etc. can be used.  
We can handle this issue by converting the column containing dates to the DateTime format. Let's take another Series example:

In [106]:
dates = pd.Series(['2022-12-01', '01/02/2022', '2022-03-23', '03/02/2022', '3 4 2023', '2023.9.30'])
dates

0    2022-12-01
1    01/02/2022
2    2022-03-23
3    03/02/2022
4      3 4 2023
5     2023.9.30
dtype: object

Now, let's convert them into the yyyy-mm-dd format:

In [107]:
pd.to_datetime(dates, format='mixed', dayfirst=True)

0   2022-12-01
1   2022-02-01
2   2022-03-23
3   2022-02-03
4   2023-04-03
5   2023-09-30
dtype: datetime64[ns]

And we got a datetime64 dtype Series. Here,
- format='mixed': specifies that the format of each given date can be different.
- dayfirst=True: specifies that the day should be considered before the month when interpreting dates.

### Handling Wrong Data

Sometimes, a dataset can have inaccurate entries due to reasons such as human errors during data input, sourcing data from unreliable places, etc.  
We can handle such wrong data in the following ways:
- Replace Individual Values
- Replace Values Based on a Condition
- Remove Wrong Values

Let's make a simple dataframe for understanding these techniques:

In [108]:
friends = pd.DataFrame({
    "name": ['Alex', 'Bob', 'Charles', 'Diana/'],
    "age": [20, 88, 21, 19],
    "gender": ['M', 'M', 'F', 'F']
})
friends

name  age gender
0     Alex   20      M
1      Bob   88      M
2  Charles   21      F
3   Diana/   19      F

Now, let's first see what are the mistakes in this DataFrame:
- Bob's age is 88 which is not very possible if all these are friends.
- Charles' gender is Female.
- Diana's name is wrong, it has a front-slash in it.

#### Replace Individual Values

We are going to replace the wrong gender value of Charles with the right one:

In [109]:
friends.loc[2, 'gender'] = 'M'
friends

name  age gender
0     Alex   20      M
1      Bob   88      M
2  Charles   21      M
3   Diana/   19      F

#### Replace Values Based on a Condition

We are going to replace all the wrong age values (only one, 88) with NaN:

In [110]:
for friend in friends.index:
    if friends.loc[friend, 'age'] > 25:
        friends.loc[friend, 'age'] = None
friends

name   age gender
0     Alex  20.0      M
1      Bob   NaN      M
2  Charles  21.0      M
3   Diana/  19.0      F

#### Remove Wrong Values

We are going to remove all the rows which has names with non-alphabet characters in it (only one, 'Diana/'):

In [111]:
import re
for friend in friends.index:
    if bool(re.search(r'[^a-zA-Z]', friends.loc[friend, 'name'])):
        friends.drop(friend, inplace=True)
friends

name   age gender
0     Alex  20.0      M
1      Bob   NaN      M
2  Charles  21.0      M

### Dummies

A dummy variable is a numerical representation used to encode categorical data. Dummy variables exhibit binary values, exclusively 0 or 1.  
In the context of a dummy variable:
- The value 1 signifies the existence of a specific category.
- The value 0 signifies the non-existence of a particular category.

We use the get_dummies() function to transform categorical variables into binary values.

In [112]:
colors = pd.Series(["Red", "Yellow", "Blue", "Red", "Yellow"])
colors

0       Red
1    Yellow
2      Blue
3       Red
4    Yellow
dtype: object

In [113]:
pd.get_dummies(colors)

Blue    Red  Yellow
0  False   True   False
1  False  False    True
2   True  False   False
3  False   True   False
4  False  False    True

Here we can see, at each index there is only one color which has valur True. We can use this method with DataFrames too.  
We can use prefix parameter to add a prefix bebfore the color name:

In [114]:
pd.get_dummies(colors, prefix='Color')

Color_Blue  Color_Red  Color_Yellow
0       False       True         False
1       False      False          True
2        True      False         False
3       False       True         False
4       False      False          True

Here we got Color_ prefix before every color name.

### Categorical

Categorical data is a type of data that represents categories or labels rather than numerical values. In simple words, it is a way of classifying into distinct categories, such as genders, country names, or education levels. Categorical data is handy when we have data that naturally fit into predefined options.

#### Create a Category

Let's create a category:

In [115]:
pd.Categorical(["Red", "Yellow", "Blue", "Red", "Yellow"])

['Red', 'Yellow', 'Blue', 'Red', 'Yellow']
Categories (3, object): ['Blue', 'Red', 'Yellow']

The output included the original data values and a list of unique categories present in the data. We can also convert a Series into a Categorical using astype() function:

In [116]:
colors

0       Red
1    Yellow
2      Blue
3       Red
4    Yellow
dtype: object

In [117]:
colors.astype('category')

0       Red
1    Yellow
2      Blue
3       Red
4    Yellow
dtype: category
Categories (3, object): ['Blue', 'Red', 'Yellow']

We can also create a Series with dtype category:

In [118]:
pd.Series(["Red", "Yellow", "Blue", "Red", "Yellow"], dtype='category')

0       Red
1    Yellow
2      Blue
3       Red
4    Yellow
dtype: category
Categories (3, object): ['Blue', 'Red', 'Yellow']

<img src="https://atharvsuryavanshi.github.io/Diagram-Manager/images/pandas-how-category-works-example.png" alt="pandas-how-category-works-example.png" width="1000">

(If the image isn't visible then click here: [How Pandas Category Works?](https://atharvsuryavanshi.github.io/Diagram-Manager/images/pandas-how-category-works-example.png))

#### Access Categories and Codes

The cat accessor allows us to access categories and codes. Here's the attributes provided by the cat accessor to access categories and codes:
- categories - Returns the unique categories present in the categorical variable.
- codes - Returns the integer codes representing the categories for each element in the categorical variable.

In [119]:
colors_cat = colors.astype('category')
colors_cat

0       Red
1    Yellow
2      Blue
3       Red
4    Yellow
dtype: category
Categories (3, object): ['Blue', 'Red', 'Yellow']

In [120]:
colors_cat.cat.categories

Index(['Blue', 'Red', 'Yellow'], dtype='object')

In [121]:
colors_cat.cat.codes

0    1
1    2
2    0
3    1
4    2
dtype: int8

**Note:** We cannot use this cat accessor on Categorical directly as we don't need it, we need it for a Categorical Series. 

#### Rename Categories

In [122]:
alphabets = pd.Series(['A', 'B', 'C', 'A', 'B'], dtype="category")
alphabets

0    A
1    B
2    C
3    A
4    B
dtype: category
Categories (3, object): ['A', 'B', 'C']

In [123]:
alphabets.cat.rename_categories({'A': 'a', 'C': 'c'})

0    a
1    B
2    c
3    a
4    B
dtype: category
Categories (3, object): ['a', 'B', 'c']

Here, we renamed 2 out of the 3 categories of the alphabets Categorical Series.

#### Add New Categories

In [124]:
alphabets.cat.add_categories(['D', 'E'])

0    A
1    B
2    C
3    A
4    B
dtype: category
Categories (5, object): ['A', 'B', 'C', 'D', 'E']

So, now it has total 5 categories.

#### Remove Categories

In [125]:
alphabets.cat.remove_categories(['B'])

0      A
1    NaN
2      C
3      A
4    NaN
dtype: category
Categories (2, object): ['A', 'C']

As we removed the category B from the Categorical Series, we now have NaN as the categories at indices 1 and 4.

#### Check if Categorical Variable is Ordered or Not

To check if a categorical variable is ordered, you can use the ordered attribute provided by the cat accessor.

In [126]:
alphabets.cat.ordered

False

That means its isn't ordered. Let's make an ordered Categorical using the alphabets Categorical Series:

In [127]:
alphabets_ordered = pd.Categorical(alphabets, ordered=True)
alphabets_ordered

['A', 'B', 'C', 'A', 'B']
Categories (3, object): ['A' < 'B' < 'C']

In [128]:
alphabets_ordered.ordered

True

Because we set ordered parameter as True, the Categorical is ordered.  
**Note:** Ordering categorical variables in Pandas helps in maintaining a logical sequence for analysis and visualization. Recognizing this order ensures accurate statistical tests, meaningful visual representations, and consistent data interpretation.

## Data Analysis and Aggregation

### DateTime

DateTime is a data type that represents a single point in time. It is especially useful when dealing with time-series data like stock prices, weather records, economic indicators etc.  
We use the to_datetime() function to convert strings to the DateTime object.

In [129]:
datetime = pd.to_datetime("2000-04-13 16:44:00")
datetime

Timestamp('2000-04-13 16:44:00')

Let's check it's type:

In [130]:
type(datetime)

pandas._libs.tslibs.timestamps.Timestamp

That means it's a Timestamp. Now, let's bring our reelers DataFrame:

In [131]:
reelers

name        username date of joining  number of reels  followers
0      Emma Watson   emma_watson01      2023-02-14              5.0    10000.0
1         John Doe     john.doe_02      2023-01-21             20.0    15000.0
2             None      a.smith_03            None              NaN        NaN
3  Michael Johnson      michael123      2023-03-15             15.0    20000.0
4             None  sophia.brown05            None              NaN        NaN
5     Ethan Miller      e.miller06      2023-04-20             25.0    25000.0
6     Olivia Davis  olivia-davis07      2023-06-18             30.0    30000.0
7             None       william_w            None              NaN        NaN
8       Ava Taylor       avataylor      2023-07-25             22.0    35000.0
9             None     dmartinez10            None              NaN        NaN

If we check the first element of the date of joining column:

In [132]:
reelers.loc[0, 'date of joining']

'2023-02-14'

It's a string. That means all the dates here are also strings, let's convert them into DateTime:

In [133]:
reelers.loc[:, ['date of joining']] = pd.to_datetime(reelers['date of joining'])
reelers

name        username      date of joining  number of reels  \
0      Emma Watson   emma_watson01  2023-02-14 00:00:00              5.0   
1         John Doe     john.doe_02  2023-01-21 00:00:00             20.0   
2             None      a.smith_03                  NaT              NaN   
3  Michael Johnson      michael123  2023-03-15 00:00:00             15.0   
4             None  sophia.brown05                  NaT              NaN   
5     Ethan Miller      e.miller06  2023-04-20 00:00:00             25.0   
6     Olivia Davis  olivia-davis07  2023-06-18 00:00:00             30.0   
7             None       william_w                  NaT              NaN   
8       Ava Taylor       avataylor  2023-07-25 00:00:00             22.0   
9             None     dmartinez10                  NaT              NaN   

   followers  
0    10000.0  
1    15000.0  
2        NaN  
3    20000.0  
4        NaN  
5    25000.0  
6    30000.0  
7        NaN  
8    35000.0  
9        NaN

Now, the column has both date and time values, if we check it's first element:

In [134]:
reelers.loc[0, 'date of joining']

Timestamp('2023-02-14 00:00:00')

That means all the dates in the column are converted into Timestamp.  
By default the format which it requires is yyyy-mm-dd, but we can use other formats too:

In [135]:
pd.to_datetime("13-04-2000 16:44:00", dayfirst=True)

Timestamp('2000-04-13 16:44:00')

Here, we put a date in dd-mm-yyyy format. It converted it into a Timestamp. We can also use custom formats too:

In [136]:
pd.to_datetime("13-04 2000 16::44::00", format="%d-%m %Y %H::%M::%S")

Timestamp('2000-04-13 16:44:00')

So, it converted a date with dd-mm yyyy HH::MM::SS format into a Timestamp.  
To get the vlues of a Timestamp, we use dt accessor:

In [137]:
reelers['date of joining'].astype('datetime64[ns]').dt.year

0    2023.0
1    2023.0
2       NaN
3    2023.0
4       NaN
5    2023.0
6    2023.0
7       NaN
8    2023.0
9       NaN
Name: date of joining, dtype: float64

Just like this, we can use month and day to get the respective values. We can also get weekday names:

In [138]:
reelers['date of joining'].astype('datetime64[ns]').dt.day_name()

0      Tuesday
1     Saturday
2          NaN
3    Wednesday
4          NaN
5     Thursday
6       Sunday
7          NaN
8      Tuesday
9          NaN
Name: date of joining, dtype: object

And here we got days. We can also check which week it is:

In [139]:
reelers['date of joining'].astype('datetime64[ns]').dt.isocalendar().week

0       7
1       3
2    <NA>
3      11
4    <NA>
5      16
6      24
7    <NA>
8      30
9    <NA>
Name: week, dtype: UInt32

And we got the numbers of the weeks. We can also check whether it is a leap year or not:

In [140]:
reelers['date of joining'].astype('datetime64[ns]').dt.is_leap_year

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: date of joining, dtype: bool

Because all the date's were from 2023 and because it wasn't a leap year, we got Flase for all the values.

DateTime index in uses DateTime values as index values.  
A datetime index is particularly useful when dealing with time series data like weather data, stock prices, and other time-dependent data, as it allows natural organization and manipulation based on timestamps.

In [141]:
new_temperatures = pd.DataFrame({'temperatures': [20.1, 22, 33.2, 44.4, 45]}, 
                                index=pd.to_datetime(['2023-12-01', '2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01']))
new_temperatures

temperatures
2023-12-01          20.1
2024-01-01          22.0
2024-02-01          33.2
2024-03-01          44.4
2024-04-01          45.0

In [142]:
new_temperatures.index

DatetimeIndex(['2023-12-01', '2024-01-01', '2024-02-01', '2024-03-01',
               '2024-04-01'],
              dtype='datetime64[ns]', freq=None)

That means, now the DataFrame has DatetimeIndex.

### Aggregate Function

Aggregate function performs summary computations on data, often on grouped data. But it can also be used on Series objects.  
This can be really useful for tasks such as calculating mean, sum, count, and other statistics for different groups within our data.

It has the following parameters:
- func - an aggregate function like sum, mean, etc.
- axis - specifies whether to apply the aggregation operation along rows or columns.
- \*args and \**kwargs - additional arguments that can be passed to the aggregation functions.

Let's bring our students DataFrame for this:

In [143]:
students

name  marathi  maths  science  history
0   Rohan       85     95       88       80
1   Soham       78     88       91       85
2  Tanmay       92     84       90       78

Now, let's take an example of mean marks for marathi subject:

In [144]:
students['marathi'].aggregate('mean')

85.0

That means the mean marks in marathi subject are 85.

In [145]:
students['history'].aggregate(['mean', 'max', 'min', 'sum'])

mean     81.0
max      85.0
min      78.0
sum     243.0
Name: history, dtype: float64

Let's take another example:

In [146]:
toys = pd.DataFrame({
    "toy": ["Car", "Doll", "Ball", "Train", "Plane", "Blocks", "Teddy Bear", "Puzzle"],
    "color": ["Red", "Blue", "Yellow", "Red", "Blue", "Yellow", "Red", "Blue"]
})
toys

toy   color
0         Car     Red
1        Doll    Blue
2        Ball  Yellow
3       Train     Red
4       Plane    Blue
5      Blocks  Yellow
6  Teddy Bear     Red
7      Puzzle    Blue

Let's count the number of items of each color:

In [147]:
toys.groupby('color')['toy'].agg('count')

color
Blue      3
Red       3
Yellow    2
Name: toy, dtype: int64

agg() is same as aggregate(). We first grouped the toys DataFrame based on the color column and then did the count for each color.

### Group By

The groupby operation lets us group data based on specific columns. This means we can divide a DataFrame into smaller groups based on the values in these columns.  
Once grouped, we can then apply functions to each group separately. These functions help summarize or aggregate the data in each group.

#### Group by a Single Column

We use the groupby() function to group data by a single column and then calculate the aggregates. Let's take an example:

In [148]:
toys.groupby('color').count()

toy
color      
Blue      3
Red       3
Yellow    2

Here, we again took counts for different colors but thi time we used count() method.

#### Group by a Multiple Columns

Let's make a new DataFrame:

In [149]:
pupils = pd.DataFrame({
    "name": ["Aarav", "Vivaan", "Ananya", "Riya", "Ishaan", "Meera", "Arjun", "Neha", "Karan", "Pooja"],
    "age": [14, 15, 13, 14, 15, 13, 14, 15, 13, 14],
    "gender": ["Male", "Male", "Female", "Female", "Male", "Female", "Male", "Female", "Male", "Female"],
    "marks": [85, 78, 92, 88, 74, 90, 79, 85, 82, 80],
    "grade": ["B", "C", "A", "A", "C", "A", "C", "B", "B", "B"]
})
pupils

name  age  gender  marks grade
0   Aarav   14    Male     85     B
1  Vivaan   15    Male     78     C
2  Ananya   13  Female     92     A
3    Riya   14  Female     88     A
4  Ishaan   15    Male     74     C
5   Meera   13  Female     90     A
6   Arjun   14    Male     79     C
7    Neha   15  Female     85     B
8   Karan   13    Male     82     B
9   Pooja   14  Female     80     B

Now, if we group it by grade and gender then:

In [150]:
pupils.groupby(['grade', 'gender'])[['age', 'marks']].agg(['count', 'mean', 'min', 'max', 'sum'])

age                        marks                   
             count       mean min max sum count  mean min max  sum
grade gender                                                      
A     Female     3  13.333333  13  14  40     3  90.0  88  92  270
B     Female     2  14.500000  14  15  29     2  82.5  80  85  165
      Male       2  13.500000  13  14  27     2  83.5  82  85  167
C     Male       3  14.666667  14  15  44     3  77.0  74  79  231

We only selected age and marks columns because we can perform mean, min, max and sum on them.

### Filtering

Filtering data is a common operation in data analysis. Pandas allows us to filter data based on different conditions.  
We can filter the data in Pandas in two main ways:
- By column names (Labels)
- By the actual data inside (Values)

Let's first bring our boys DataFrame:

In [151]:
boys

name         dob  age       city
0   Aarav  2001-05-14   23     Mumbai
1  Vivaan  2003-08-21   20      Delhi
2  Aditya  2000-12-05   24  Bangalore
3  Vihaan  2002-07-18   21     Mumbai
4   Arjun  1999-11-11   25  Hyderabad
5     Sai  2005-03-30   19       Pune
6   Rishi  2004-09-25   20    Kolkata
7   Aryan  2001-06-01   23      Delhi
8   Dhruv  2003-10-12   20  Bangalore
9   Kabir  2004-04-17   19     Mumbai

#### Filter Data by Labels

We can use the filter() function to select columns by their names or labels:

In [152]:
boys.filter(['name', 'city'])

name       city
0   Aarav     Mumbai
1  Vivaan      Delhi
2  Aditya  Bangalore
3  Vihaan     Mumbai
4   Arjun  Hyderabad
5     Sai       Pune
6   Rishi    Kolkata
7   Aryan      Delhi
8   Dhruv  Bangalore
9   Kabir     Mumbai

And we got all the names and their respective cities.

#### Filter Data by Values

We can also filter data by values. Some of the common ways to filter data by values are:
- Using logical operators.
- Using the isin() method.
- Using the str cccessor.
- Using the query() method.

##### By using logical operators

In [153]:
boys[boys.age > 20]

name         dob  age       city
0   Aarav  2001-05-14   23     Mumbai
2  Aditya  2000-12-05   24  Bangalore
3  Vihaan  2002-07-18   21     Mumbai
4   Arjun  1999-11-11   25  Hyderabad
7   Aryan  2001-06-01   23      Delhi

Here we got all the boys who are older than 20 years.

##### By using the isin() method

In [155]:
boys[boys['city'].isin(['Mumbai', 'Delhi'])]

name         dob  age    city
0   Aarav  2001-05-14   23  Mumbai
1  Vivaan  2003-08-21   20   Delhi
3  Vihaan  2002-07-18   21  Mumbai
7   Aryan  2001-06-01   23   Delhi
9   Kabir  2004-04-17   19  Mumbai

And we got all the boys who live in Mumbai or Delhi.

##### By using str accessor

In [156]:
boys[boys['name'].str.startswith('A')]

name         dob  age       city
0   Aarav  2001-05-14   23     Mumbai
2  Aditya  2000-12-05   24  Bangalore
4   Arjun  1999-11-11   25  Hyderabad
7   Aryan  2001-06-01   23      Delhi

And we got all the names with the initial letter A.

##### By using query() method

This is the most flexible method for filtering a dataframe based on column values. A query containing the filtering conditions can be passed as a string to the query() method:

In [157]:
boys.query("age > 23 and name.str.startswith('A')")

name         dob  age       city
2  Aditya  2000-12-05   24  Bangalore
4   Arjun  1999-11-11   25  Hyderabad

Here, we got all the boys who have A as the initial letter of their names and are older than 23 years.

### Sort

Sorting is a fundamental operation in data manipulation and analysis that involves arranging data in a specific order.  
Sorting is crucial for tasks such as organizing data for better readability, identifying patterns, making comparisons, and facilitating further analysis.  
Let's try this on our boys DataFrame:

In [158]:
boys

name         dob  age       city
0   Aarav  2001-05-14   23     Mumbai
1  Vivaan  2003-08-21   20      Delhi
2  Aditya  2000-12-05   24  Bangalore
3  Vihaan  2002-07-18   21     Mumbai
4   Arjun  1999-11-11   25  Hyderabad
5     Sai  2005-03-30   19       Pune
6   Rishi  2004-09-25   20    Kolkata
7   Aryan  2001-06-01   23      Delhi
8   Dhruv  2003-10-12   20  Bangalore
9   Kabir  2004-04-17   19     Mumbai

We can sort values using sort_values() function:

In [159]:
boys.sort_values('age')

name         dob  age       city
5     Sai  2005-03-30   19       Pune
9   Kabir  2004-04-17   19     Mumbai
1  Vivaan  2003-08-21   20      Delhi
6   Rishi  2004-09-25   20    Kolkata
8   Dhruv  2003-10-12   20  Bangalore
3  Vihaan  2002-07-18   21     Mumbai
0   Aarav  2001-05-14   23     Mumbai
7   Aryan  2001-06-01   23      Delhi
2  Aditya  2000-12-05   24  Bangalore
4   Arjun  1999-11-11   25  Hyderabad

It sorted out the rows based on the age column values in an ascending order. Now, let's try the descending order:

In [160]:
boys.sort_values('city', ascending=False)

name         dob  age       city
5     Sai  2005-03-30   19       Pune
0   Aarav  2001-05-14   23     Mumbai
3  Vihaan  2002-07-18   21     Mumbai
9   Kabir  2004-04-17   19     Mumbai
6   Rishi  2004-09-25   20    Kolkata
4   Arjun  1999-11-11   25  Hyderabad
1  Vivaan  2003-08-21   20      Delhi
7   Aryan  2001-06-01   23      Delhi
2  Aditya  2000-12-05   24  Bangalore
8   Dhruv  2003-10-12   20  Bangalore

It sorted out the rows based on the city column values in a descending order. Now let's sort the DataFrame based on age in an ascending order and city in a descending order:

In [161]:
boys.sort_values(['age', 'city'], ascending=[True, False])

name         dob  age       city
5     Sai  2005-03-30   19       Pune
9   Kabir  2004-04-17   19     Mumbai
6   Rishi  2004-09-25   20    Kolkata
1  Vivaan  2003-08-21   20      Delhi
8   Dhruv  2003-10-12   20  Bangalore
3  Vihaan  2002-07-18   21     Mumbai
0   Aarav  2001-05-14   23     Mumbai
7   Aryan  2001-06-01   23      Delhi
2  Aditya  2000-12-05   24  Bangalore
4   Arjun  1999-11-11   25  Hyderabad

It sorted out the rows based on the age column values in an ascending order and then based on the city column values in a descending order. We can also sort Series using this function.  
We can also sort based on indices, we use sort_index() function for that. Let's sort the boys DataFrame based on the indices in a descending order:

In [162]:
boys.sort_index(ascending=False)

name         dob  age       city
9   Kabir  2004-04-17   19     Mumbai
8   Dhruv  2003-10-12   20  Bangalore
7   Aryan  2001-06-01   23      Delhi
6   Rishi  2004-09-25   20    Kolkata
5     Sai  2005-03-30   19       Pune
4   Arjun  1999-11-11   25  Hyderabad
3  Vihaan  2002-07-18   21     Mumbai
2  Aditya  2000-12-05   24  Bangalore
1  Vivaan  2003-08-21   20      Delhi
0   Aarav  2001-05-14   23     Mumbai

### Correlation

Correlation is a statistical concept that quantifies the degree to which two variables are related to each other.  
Correlation can be calculated in Pandas using the corr() function.

In [163]:
studies = pd.DataFrame({
    "name": ["Aarav", "Vivaan", "Ananya", "Riya", "Ishaan", "Meera", "Arjun", "Neha"],
    "study hours": [2, 1, 4, 3, 1.5, 3.5, 2.5, 2],
    "marks": [70, 55, 95, 85, 60, 90, 75, 80]
})
studies

name  study hours  marks
0   Aarav          2.0     70
1  Vivaan          1.0     55
2  Ananya          4.0     95
3    Riya          3.0     85
4  Ishaan          1.5     60
5   Meera          3.5     90
6   Arjun          2.5     75
7    Neha          2.0     80

Now, let's check the correlation between study hours and marks:

In [164]:
studies[['study hours', 'marks']].corr()

study hours     marks
study hours     1.000000  0.955485
marks           0.955485  1.000000

The output is a correlation matrix that displays the correlation coefficients between all pairs of columns in the dataframe. In this case, there were only two columns, so the output matrix is 2 by 2.  
Here, the correlation coefficient between study hours and marks is 0.955485, which is positive. This indicates that **as the study hours increase, the marks also increase**.  
The coefficient value of 1.000000 along the diagonal represents the correlation of each column with itself.

#### Positive and Negative Correlation

**Positive correlation** refers to a relationship between two variables where they both tend to change in the same direction. When one variable increases, the other variable also tends to increase, and when one variable decreases, the other variable also tends to decrease.  
**Negative correlation**, on the other hand, refers to a relationship between two variables where they tend to change in opposite directions. When one variable increases, the other variable tends to decrease, and vice versa.

<img src="https://atharvsuryavanshi.github.io/Diagram-Manager/images/pandas-correlation-example.png" alt="pandas-correlation-example.png" width="1000">

(If the image isn't visible then click here: [Pandas Correlation](https://atharvsuryavanshi.github.io/Diagram-Manager/images/pandas-correlation-example.png))

As we can see in the above graphs, when the temperatures increase, the tea sales start decreasing. But the exactly apposite happens with the kulfi sales where they increase w. r. to increase in temperature.  
Let's check the correlation for the tea sales data:

In [165]:
tea_sales = pd.DataFrame({
    "temperature": [10, 15, 20, 25, 30, 35],
    "sales": [480, 445, 390, 335, 310, 240]
})
tea_sales.corr()

temperature     sales
temperature     1.000000 -0.994737
sales          -0.994737  1.000000

The correlation coefficient is negative, which indicates the decrease in tea sales w. r. to increase in temperature. This is **negative correlation**.  
Now, let's check the correlation for the kulfi sales data:

In [166]:
kulfi_sales = pd.DataFrame({
    "temperature": [10, 15, 20, 25, 30, 35],
    "sales": [110, 155, 200, 240, 310, 360]
})
kulfi_sales.corr()

temperature     sales
temperature     1.000000  0.996378
sales           0.996378  1.000000

The correlation coefficient is positive, which indicates the increase in kulfi sales w. r. to increase in temperature. This is **positive correlation**.

#### Correlation between Two Columns

We can directly check for the correlation coefficient related to two column values. For example:

In [167]:
studies['study hours'].corr(studies['marks'])

0.95548517149766

Switching the column positions won't change here anything:

In [168]:
studies['marks'].corr(studies['study hours'])

0.95548517149766

#### Handeling Missing Values

DataFrame may contain missing values (NaN). The corr() function completely ignores the rows with NaN values:

In [169]:
reelers

name        username      date of joining  number of reels  \
0      Emma Watson   emma_watson01  2023-02-14 00:00:00              5.0   
1         John Doe     john.doe_02  2023-01-21 00:00:00             20.0   
2             None      a.smith_03                  NaT              NaN   
3  Michael Johnson      michael123  2023-03-15 00:00:00             15.0   
4             None  sophia.brown05                  NaT              NaN   
5     Ethan Miller      e.miller06  2023-04-20 00:00:00             25.0   
6     Olivia Davis  olivia-davis07  2023-06-18 00:00:00             30.0   
7             None       william_w                  NaT              NaN   
8       Ava Taylor       avataylor  2023-07-25 00:00:00             22.0   
9             None     dmartinez10                  NaT              NaN   

   followers  
0    10000.0  
1    15000.0  
2        NaN  
3    20000.0  
4        NaN  
5    25000.0  
6    30000.0  
7        NaN  
8    35000.0  
9        NaN

In [170]:
reelers['followers'].corr(reelers['number of reels'])

0.7689578149010814

#### Correlation Methods

We can calculate correlation using three different methods in Pandas:
- Pearson Method (default): evaluates the linear relationship between two continuous variables.
- Kendall Method: measures the ordinal association between two measured quantities.
- Spearman Method: evaluates the monotonic relationship between two continuous or ordinal variables.

By default, corr() computes the Pearson correlation coefficient, which measures the linear relationship between two variables. Let's try the remaining two.

##### Using Kendall Method

In [171]:
studies['marks'].corr(studies['marks'], method='kendall')

0.9999999999999998

##### Using Spearman Method

In [172]:
studies['marks'].corr(studies['marks'], method='spearman')

1.0

So, what we got so far for the studies DataFrame is:

| Method | Correlation Coefficient |
|--------|-------------------------|
| Pearson | 0.95548517149766 |
| Kendall | 0.9999999999999998 |
| Spearman | 1.0 |

If the Pearson's coefficient has the highest value then the correlation is mostly linear.

#### Perfect, Good & Bad Correlations

##### Perfect Correlation

A perfect positive correlation implies that for every increase in one variable, there is a proportionate increase in the other variable, indicated by a coefficient of +1.  
A perfect negative correlation, represented by -1, signifies that an increase in one variable leads to a proportionate decrease in the other.

##### Good Correlation

A good correlation can range from 0.5 to 0.9 (positive or negative) and generally indicates a strong relationship between the variables, but it doesn't mean the relationship is perfect.

##### Bad Correlation

A bad correlation is typically close to zero, indicating that there is no relationship or any form of dependence between the two variables.

Let's create three different real-world examples to illustrate perfect, good, and bad correlations:
- Perfect Correlation: Distance traveled by a car and fuel consumed (assuming constant fuel efficiency).
- Good Correlation: Number of hours studied and exam scores (typically, more study hours lead to better scores, but with some variability).
- Bad Correlation: Number of ice creams sold and the number of people who went to the gym (these two might have little to no correlation).

<img src="https://atharvsuryavanshi.github.io/Diagram-Manager/images/pandas-perfect-good-bad-correlation-example.png" alt="pandas-perfect-good-bad-correlation-example.png" width="1000">

(If the image isn't visible then click here: [Pandas Perfect, Good and Bad Correlation](https://atharvsuryavanshi.github.io/Diagram-Manager/images/pandas-perfect-good-bad-correlation-example.png))

## Additional Functionalities

### Merge

The merge operation merges two DataFrames based on their indexes or a specified column. The merge() in Pandas works similar to JOINs in SQL.  
Let's take the famous employees and departments example:

In [173]:
employees = pd.DataFrame({
    "id": ["E001", "E002", "E003", "E004", "E005", "E006", "E007", "E008"],
    "employee name": ["Rahul", "Priya", "Amit", "Sonia", "Vikas", "Nisha", "Karan", "Meena"],
    "department id": ["D001", "D002", "D001", "D003", "D002", "D003", "D001", "D002"],
    "salary": [50000, 60000, 55000, 62000, 58000, 60000, 52000, 59000]
})
employees

id employee name department id  salary
0  E001         Rahul          D001   50000
1  E002         Priya          D002   60000
2  E003          Amit          D001   55000
3  E004         Sonia          D003   62000
4  E005         Vikas          D002   58000
5  E006         Nisha          D003   60000
6  E007         Karan          D001   52000
7  E008         Meena          D002   59000

In [174]:
departments = pd.DataFrame({
    "department id": ["D001", "D002", "D003"],
    "department name": ["IT", "HR", "Finance"]
})
departments

department id department name
0          D001              IT
1          D002              HR
2          D003         Finance

Now, let's perform the merge operation:

In [175]:
pd.merge(employees, departments, on='department id')

id employee name department id  salary department name
0  E001         Rahul          D001   50000              IT
1  E002         Priya          D002   60000              HR
2  E003          Amit          D001   55000              IT
3  E004         Sonia          D003   62000         Finance
4  E005         Vikas          D002   58000              HR
5  E006         Nisha          D003   60000         Finance
6  E007         Karan          D001   52000              IT
7  E008         Meena          D002   59000              HR

ANd we got a merged DataFrame.  
For the merge() function, we can pass the following parameters:
- left: specifies the left DataFrame to be merged.
- right: specifies the right DataFrame to be merged.
- on (optional): specifies column(s) to join on.
- how (optional): specifies the type of join to perform.
- left_on (optional): specifies column(s) from the left DataFrame to use as key(s) for merging.
- right_on (optional): specifies column(s) from the right DataFrame to use as key(s) for merging.
- sort (optional): if True, sort the result DataFrame by the join keys.

Types of Join Operations In merge():
- Inner Join (default)
- Left Join
- Right Join
- Outer Join
- Cross Join

An **inner join** combines two DataFrames based on a common key and returns a new DataFrame that contains only rows that have matching values in both of the original DataFrames.

A **left join** combines two DataFrames based on a common key and returns a new DataFrame that contains all rows from the left DataFrame and the matched rows from the right DataFrame. If values are not found in the right dataframe, it fills the space with NaN.

A **right join** is the opposite of a left join. It returns a new DataFrame that contains all rows from the right DataFrame and the matched rows from the left DataFrame. If values are not found in the left dataframe, it fills the space with NaN.

An **outer join** combines two DataFrames based on a common key. Unlike an inner join, an outer join returns a new DataFrame that contains all rows from both original DataFrames. If values are not found in the DataFrames, it fills the space with NaN.

A **cross join** in Pandas creates the cartesian product of both DataFrames while preserving the order of the left DataFrame.

Let's take a cross join example:

In [176]:
pd.merge(employees, departments, how='cross')

id employee name department id_x  salary department id_y department name
0   E001         Rahul            D001   50000            D001              IT
1   E001         Rahul            D001   50000            D002              HR
2   E001         Rahul            D001   50000            D003         Finance
3   E002         Priya            D002   60000            D001              IT
4   E002         Priya            D002   60000            D002              HR
5   E002         Priya            D002   60000            D003         Finance
6   E003          Amit            D001   55000            D001              IT
7   E003          Amit            D001   55000            D002              HR
8   E003          Amit            D001   55000            D003         Finance
9   E004         Sonia            D003   62000            D001              IT
10  E004         Sonia            D003   62000            D002              HR
11  E004         Sonia            D003   62000            D003         Finance
12  E005         Vikas            D002   58000            D001              IT
13  E005         Vikas            D002   58000            D002              HR
14  E005         Vikas            D002   58000            D003         Finance
15  E006         Nisha            D003   60000            D001              IT
16  E006         Nisha            D003   60000            D002              HR
17  E006         Nisha            D003   60000            D003         Finance
18  E007         Karan            D001   52000            D001              IT
19  E007         Karan            D001   52000            D002              HR
20  E007         Karan            D001   52000            D003         Finance
21  E008         Meena            D002   59000            D001              IT
22  E008         Meena            D002   59000            D002              HR
23  E008         Meena            D002   59000            D003         Finance

### Join

The join operation in Pandas joins two DataFrames based on their indexes.

In [177]:
employees.join(departments, lsuffix=' 1st', rsuffix=' 2nd')

id employee name department id 1st  salary department id 2nd  \
0  E001         Rahul              D001   50000              D001   
1  E002         Priya              D002   60000              D002   
2  E003          Amit              D001   55000              D003   
3  E004         Sonia              D003   62000               NaN   
4  E005         Vikas              D002   58000               NaN   
5  E006         Nisha              D003   60000               NaN   
6  E007         Karan              D001   52000               NaN   
7  E008         Meena              D002   59000               NaN   

  department name  
0              IT  
1              HR  
2         Finance  
3             NaN  
4             NaN  
5             NaN  
6             NaN  
7             NaN

Here it doesn't make much sense with this example but is useful when we want to perform joins based on the indices.  
For the join() function, we can pass the following parameters:
- other: is the DataFrame to be joined to the first DataFrame.
- on(optional): specifies the index column(s) based on which the DataFrames are joined.
- how(optional): specifies the type of join to perform (left join by default).
- lsuffix(optional): specifies a suffix that will be appended to a column name of the first DataFrame if there is a collision or conflict with another column name.
- rsuffix(optional): specifies a suffix that will be appended to a column name of the second DataFrame if there is a collision or conflict with another column name.
- sort(optional): determines whether to sort the result DataFrame by the join keys.

### Concatenation

The concatenation operation in Pandas appends one DataFrame to another along an axis. It works similar to SQL UNION ALL operation.  
We use the concat() method to concatenate two or more DataFrames in Pandas.

In [178]:
pd.concat([employees, departments])

id employee name department id   salary department name
0  E001         Rahul          D001  50000.0             NaN
1  E002         Priya          D002  60000.0             NaN
2  E003          Amit          D001  55000.0             NaN
3  E004         Sonia          D003  62000.0             NaN
4  E005         Vikas          D002  58000.0             NaN
5  E006         Nisha          D003  60000.0             NaN
6  E007         Karan          D001  52000.0             NaN
7  E008         Meena          D002  59000.0             NaN
0   NaN           NaN          D001      NaN              IT
1   NaN           NaN          D002      NaN              HR
2   NaN           NaN          D003      NaN         Finance

For the concat function, we can pass the following parameters:
- objs: sequence of Series or DataFrame objects.
- axis (optional): the axis to concatenate along.
- join (optional): the type of join to perform.
- ignore_index (optional): if True, it will not use the index values on the concatenation axis and will result in a default integer index.
- keys (optional): used to construct hierarchical index using the passed keys as the outermost level.
- verify_integrity (optional): If True, it checks whether the new concatenated axis contains duplicates and raises ValueError if duplicates are found.
- sort (optional): sorts the non-concatenation axis if it is not already aligned.

Let's try concat() along the axis 1:

In [179]:
pd.concat([employees, departments], axis=1)

id employee name department id  salary department id department name
0  E001         Rahul          D001   50000          D001              IT
1  E002         Priya          D002   60000          D002              HR
2  E003          Amit          D001   55000          D003         Finance
3  E004         Sonia          D003   62000           NaN             NaN
4  E005         Vikas          D002   58000           NaN             NaN
5  E006         Nisha          D003   60000           NaN             NaN
6  E007         Karan          D001   52000           NaN             NaN
7  E008         Meena          D002   59000           NaN             NaN

It's similar to the join operation on these two tables.

There are three different methods to combine DataFrames in Pandas:
- join(): joins two DataFrames based on their indexes, performs left join by default.
- merge(): joins two DataFrames based on any specified columns, performs inner join by default.
- concat(): stacks two DataFrames along the vertical or horizontal axis.

---

***EOF, happy coding!***